# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on:
- push

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - Windows-2019
        - macOS-10.15
        - Ubuntu-18.04
        - Ubuntu-20.04
        nodejs:
        - 18
      fail-fast: false
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Verify
      run: npm run verify
